### ISSUE TITLE
Jogo ideal

### ISSUE THREAD

**Issue by Davinator3000** [enzo-davi/my-game#6]
Pensar em mecânicas e ideias do jogo que tem a possibilidade de serem implementadas(ou não) conforme limitações de tempo e conhecimento de programação do aluno

**Comment by enzoocker** [comment]
Mecânicas

- Sons ambientes (portas abrindo, chuva, madeira rangendo, fogo, água);
- Sons de ações (ataque do personagem);
- Ramificações da história (suas escolhas alteram a história);
- Elementos RPG (upar personagem, precisar de requisitos mínimoas para realizar certas ações);
- Inventário (poder coletar itens);
- Imagens (imagens ilustrando o local que o personagem se encontra);
- Elementos aleatórios (rodar um dado, aumentando ou diminuindo sua chance de vitória na batalha/história);
- Criação de um personagem (escolher a aparência de seu personagem);
- Troféus/conquistas (passar por certas situações de certas formas);
- Poder jogar com diferentes personagens ao longo da história;

**Comment by Davinator3000** [comment]
Um jogo de escolhas significativas com múltiplos finais, vários personagens, ramificações extensivas e uma trama envolvente
